-- MySQL Script generated by MySQL Workbench
-- 10/01/14 11:10:57
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema anisoftera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anisoftera` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `anisoftera` ;

-- -----------------------------------------------------
-- Table `anisoftera`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Usuario` (
  `usuario` VARCHAR(100) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anisoftera`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Equipo` (
  `id` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anisoftera`.`Integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Integrante` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Integrante` (
  `id` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anisoftera`.`Proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Proyecto` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Proyecto` (
  `id` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL COMMENT 'nombre del proyecto',
  `fechaInicio` VARCHAR(20) NOT NULL,
  `fechaFin` VARCHAR(20) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `anio` INT(5) NOT NULL,
  `Equipo_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Proyecto_Equipo1`
    FOREIGN KEY (`Equipo_id`)
    REFERENCES `anisoftera`.`Equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '																																											';

CREATE INDEX `fk_Proyecto_Equipo1_idx` ON `anisoftera`.`Proyecto` (`Equipo_id` ASC);


-- -----------------------------------------------------
-- Table `anisoftera`.`Ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Ciclo` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Ciclo` (
  `numero` VARCHAR(50) NOT NULL,
  `Proyecto_id` VARCHAR(50) NOT NULL,
  `ciclo` INT NOT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `fk_Ciclo_Proyecto1`
    FOREIGN KEY (`Proyecto_id`)
    REFERENCES `anisoftera`.`Proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ciclo_Proyecto1_idx` ON `anisoftera`.`Ciclo` (`Proyecto_id` ASC);


-- -----------------------------------------------------
-- Table `anisoftera`.`Semana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Semana` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Semana` (
  `fechaInicio` VARCHAR(20) NOT NULL,
  `fechaFin` VARCHAR(20) NOT NULL,
  `numero` VARCHAR(50) NOT NULL,
  `Ciclo_numero` VARCHAR(50) NOT NULL,
  `semana` INT NOT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `fk_Semana_Ciclo1`
    FOREIGN KEY (`Ciclo_numero`)
    REFERENCES `anisoftera`.`Ciclo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Semana_Ciclo1_idx` ON `anisoftera`.`Semana` (`Ciclo_numero` ASC);


-- -----------------------------------------------------
-- Table `anisoftera`.`Usuario_has_Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Usuario_has_Equipo` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Usuario_has_Equipo` (
  `Usuario_usuario` VARCHAR(100) NOT NULL,
  `Equipo_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Usuario_usuario`, `Equipo_id`),
  CONSTRAINT `fk_Usuario_has_Equipo_Usuario1`
    FOREIGN KEY (`Usuario_usuario`)
    REFERENCES `anisoftera`.`Usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Equipo_Equipo1`
    FOREIGN KEY (`Equipo_id`)
    REFERENCES `anisoftera`.`Equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Equipo_Equipo1_idx` ON `anisoftera`.`Usuario_has_Equipo` (`Equipo_id` ASC);

CREATE INDEX `fk_Usuario_has_Equipo_Usuario1_idx` ON `anisoftera`.`Usuario_has_Equipo` (`Usuario_usuario` ASC);


-- -----------------------------------------------------
-- Table `anisoftera`.`Equipo_has_Integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Equipo_has_Integrante` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Equipo_has_Integrante` (
  `Equipo_id` VARCHAR(20) NOT NULL,
  `Integrante_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Equipo_id`, `Integrante_id`),
  CONSTRAINT `fk_Equipo_has_Integrante_Equipo1`
    FOREIGN KEY (`Equipo_id`)
    REFERENCES `anisoftera`.`Equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_has_Integrante_Integrante1`
    FOREIGN KEY (`Integrante_id`)
    REFERENCES `anisoftera`.`Integrante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Equipo_has_Integrante_Integrante1_idx` ON `anisoftera`.`Equipo_has_Integrante` (`Integrante_id` ASC);

CREATE INDEX `fk_Equipo_has_Integrante_Equipo1_idx` ON `anisoftera`.`Equipo_has_Integrante` (`Equipo_id` ASC);


-- -----------------------------------------------------
-- Table `anisoftera`.`Fase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Fase` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Fase` (
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anisoftera`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Actividad` (
  `nombre` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `horas_planeadas` INT NOT NULL,
  `minutos_planeados` INT NOT NULL,
  `horas_utilizadas` INT NOT NULL,
  `minutos_utilizados` INT NOT NULL,
  `Fase_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nombre`),
  CONSTRAINT `fk_Actividad_Fase1`
    FOREIGN KEY (`Fase_nombre`)
    REFERENCES `anisoftera`.`Fase` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Actividad_Fase1_idx` ON `anisoftera`.`Actividad` (`Fase_nombre` ASC);


-- -----------------------------------------------------
-- Table `anisoftera`.`Evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`Evaluacion` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`Evaluacion` (
  `id` VARCHAR(50) NOT NULL,
  `autoevaluacion` DOUBLE NOT NULL,
  `coevaluacion` DOUBLE NOT NULL,
  `heteroevaluacion` DOUBLE NOT NULL,
  `Integrante_id` VARCHAR(20) NOT NULL,
  `Semana_numero` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Evaluacion_Integrante1`
    FOREIGN KEY (`Integrante_id`)
    REFERENCES `anisoftera`.`Integrante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_Semana1`
    FOREIGN KEY (`Semana_numero`)
    REFERENCES `anisoftera`.`Semana` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Evaluacion_Integrante1_idx` ON `anisoftera`.`Evaluacion` (`Integrante_id` ASC);

CREATE INDEX `fk_Evaluacion_Semana1_idx` ON `anisoftera`.`Evaluacion` (`Semana_numero` ASC);


-- -----------------------------------------------------
-- Table `anisoftera`.`tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anisoftera`.`tiempo` ;

CREATE TABLE IF NOT EXISTS `anisoftera`.`tiempo` (
  `id` VARCHAR(50) NOT NULL,
  `fechaInicio` VARCHAR(45) NOT NULL,
  `fechaFin` VARCHAR(45) NOT NULL,
  `horas` INT NOT NULL,
  `reseso` INT NOT NULL,
  `comentario` VARCHAR(200) NULL,
  `Integrante_id` VARCHAR(20) NOT NULL,
  `Semana_numero` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tiempo_Integrante1`
    FOREIGN KEY (`Integrante_id`)
    REFERENCES `anisoftera`.`Integrante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiempo_Semana1`
    FOREIGN KEY (`Semana_numero`)
    REFERENCES `anisoftera`.`Semana` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tiempo_Integrante1_idx` ON `anisoftera`.`tiempo` (`Integrante_id` ASC);

CREATE INDEX `fk_tiempo_Semana1_idx` ON `anisoftera`.`tiempo` (`Semana_numero` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
